package com.learning.telusko.bo;

import lombok.Data;
import lombok.Getter;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

//POJO
//To represent Customer document data in our apllication

@Document //similar to entity of RDMS
public class Customer {
    @Id
    private String id; //object id generated by Mongodb
    private Integer cusNo;
    private String name;
    private String city;

    public Customer() {
        System.out.println("Zero params customer obj");
    }

    public Customer(Integer cusNo, String name, String city) {
        this.cusNo = cusNo;
        this.name = name;
        this.city = city;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id='" + id + '\'' +
                ", cusNo='" + cusNo + '\'' +
                ", name='" + name + '\'' +
                ", city='" + city + '\'' +
                '}';
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Integer getCusNo() {
        return cusNo;
    }

    public void setCusNo(Integer cusNo) {
        this.cusNo = cusNo;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }
}

