spring.application.name=SpringMVC02


spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
#spring.x.prefix , spring.x.suffix ->these info we are giving to view resolver

server.servlet.context-path=/jstl

server.error.whitelabel.enabled=false