spring.application.name=MCPServer2_news_server


server.port=8481

spring.ai.mcp.server.name=news-server
spring.ai.mcp.server.version=0.0.1

news.api.key=

logging.level.org.springframework.ai.mcp=INFO