spring.application.name=MCPServer2_datetime_server
server.port=8483

spring.ai.mcp.server.name=MCPServer2_datetime_server
spring.ai.mcp.server.version=0.0.1


logging.level.org.springframework.ai.mcp=INFO