spring.application.name=SpringAI01


spring.ai.openai.api-key= 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