package com.learning.telusko.dto;

//POJO

import lombok.Data;
import org.springframework.data.annotation.Id;

// DTO layer is used to transfer data from one layer to another


public class CustomerDTO {


    @Id
    private String id; //object id generated by Mongodb
    private Integer cusNo;
    private String name;
    private String city;

    public CustomerDTO() {
        System.out.println("Zero params customer obj");
    }

    public CustomerDTO(Integer cusNo, String name, String city) {
        this.cusNo = cusNo;
        this.name = name;
        this.city = city;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id='" + id + '\'' +
                ", cusNo='" + cusNo + '\'' +
                ", name='" + name + '\'' +
                ", city='" + city + '\'' +
                '}';
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Integer getCusNo() {
        return cusNo;
    }

    public void setCusNo(Integer cusNo) {
        this.cusNo = cusNo;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }
}
