package com.learning.telusko.dto;

//POJO

import lombok.Data;
import org.springframework.data.annotation.Id;

// DTO layer is used to transfer data from one layer to another


@Data
public class CustomerDTO {


    @Id
    private String id; //object id generated by Mongodb
    private String cusNo;
    private String name;
    private String city;

    public CustomerDTO() {
        System.out.println("Zero params customer obj");
    }

    public CustomerDTO(String cusNo, String name, String city) {
        this.cusNo = cusNo;
        this.name = name;
        this.city = city;
    }

    @Override
    public String toString() {
        return "Customer{" +
                "id='" + id + '\'' +
                ", cusNo='" + cusNo + '\'' +
                ", name='" + name + '\'' +
                ", city='" + city + '\'' +
                '}';
}
