spring.application.name=SpringBoot06Profile

#spring.profiles.active=microservice
## notice that only microserve bean is created and autowired to courses since microservice profile is selected
#
#spring.profiles.active=dev
# notice that tomcat is now deployed on server port 8586

#spring.profiles.active=prod

spring.profiles.active=test  
##error coz no course bean is created for this profile