spring.application.name=SpringDataJPA11MongoDB


spring.data.mongo.database=mehakdb
spring.data.mongo.port=27017
spring.data.mongo.host=localhost


# DTO layer is suer to transfer data from one layer to another